### ISSUE TITLE
Minimum deployment target is higher than needed

### ISSUE THREAD

**Issue by csknns** [hubrioAU/XRouter#25]
Hello, and thanks for the great library.
**Description**
You have in the podspec deployment_target 11.0, but I tested in iOS simulator and in builds & runs fine. Is there a reason have min deployment target iOS 11? I need to use it for a project that has min deployment target iOS 10. I run it in a iOS 10 simulator and it seems to run fine, also there are not iOS-version related warnings, but I might missing something. 

**Expected behavior**
To build with deployment_target <11.0

**Steps To Reproduce**

**Your configuration:**
 - Model: [Any]
 - iOS version: [Any]
 - Xcode version: [10.1] 
 - XRouter version: [latest]

**Comment by reececomo** [comment]
Good spot @csknns!

Nicely done on getting a PR up
